In [3]:
import urllib.request
import zipfile

url = "https://files.grouplens.org/datasets/movielens/ml-100k.zip"

# Download
urllib.request.urlretrieve(url, "ml-100k.zip")

# Unzip
with zipfile.ZipFile("ml-100k.zip", "r") as zip_ref:
    zip_ref.extractall(".")

print("Downloaded and extracted successfully!")

Downloaded and extracted successfully!

In [4]:
import numpy as np
import pandas as pd

In [5]:
data = pd.read_csv('ml-100k/u.data', sep='\t', names=['user_id', 'item_id', 'rating', 'timestamp'])
data.head()

   user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [9]:
user = pd.read_csv('ml-100k/u.user', sep='|', names=['user_id', 'age', 'gender', 'occupation', 'zip_code'])
user.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [16]:
cols = [
    "movie id" , " movie title" , "release date" , "video release date" ,
    "IMDb URL" , "unknown" , "Action" , "Adventure" , "Animation" ,
    "Children's" , "Comedy" , "Crime" , "Documentary" , "Drama" , "Fantasy" ,
    "Film-Noir" , "Horror" , "Musical" , "Mystery" , "Romance" , "Sci-Fi" ,
    "Thriller" , "War" , "Western"]
item = pd.read_csv("ml-100k/u.item", sep='|', encoding='latin-1' ,names=cols)
item.head()

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [17]:
data.shape

(100000, 4)

In [27]:
unique_item_ids = data["item_id"].nunique()
print( f"unique Item ids : { unique_item_ids } ")

unique Item ids : 1682

In [26]:
unique_user_ids = data["user_id"].nunique()
print( f"unique User ids : { unique_user_ids } ")

unique User ids : 943

In [42]:
item_id_group = data.groupby("item_id")
rating_mean_per_id = item_id_group["rating"].mean()
rating_mean_per_id

item_id
1       3.878319
2       3.206107
3       3.033333
4       3.550239
5       3.302326
          ...
1678    1.000000
1679    3.000000
1680    2.000000
1681    3.000000
1682    3.000000
Name: rating, Length: 1682, dtype: float64