In [6]:
import pandas as pd
from data import Data
obj = Data()
df = obj.data()
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
df["Name"].str.find("Mr").head()

0     8
1     9
2    -1
3    10
4     7
Name: Name, dtype: int64

In [18]:
count = df["Name"].str.contains("Mrs").sum()
print(count)

129

In [20]:
data = {
    "Name":["Sumit" , "Shivam k" , "Shivang" , "Shiva"],
    "Email":["s@gmail.com" , "t@gmail.com" , "m@gmail.com" , "p@gmail.com"]
}

df = pd.DataFrame(data)
df

       Name        Email
0     Sumit  s@gmail.com
1  Shivam k  t@gmail.com
2   Shivang  m@gmail.com
3     Shiva  p@gmail.com

In [24]:
df["Name"].str.replace("k" ,  "Kumar" , regex=False)

0           Sumit
1    Shivam Kumar
2         Shivang
3           Shiva
Name: Name, dtype: str

In [37]:
df["Name"].str.pad(width=10 , side="left" , fillchar="-")

0    -----Sumit
1    --Shivam k
2    ---Shivang
3    -----Shiva
Name: Name, dtype: str