In [26]:
import pandas as pd
import numpy as np

# matplotlib & seaborn
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(42)
n = 50

df = pd.DataFrame({
    # Nominal
    'Gender': np.random.choice(['Male','Female', 'Other'], n),
    'Color': np.random.choice(['Red', 'Blue', 'Green', 'Yellow'], n),

    # Ordinal
    'Education': np.random.choice(['High School', 'Bachelors', 'Masters', 'PhD'], n),
    'Satisfaction': np.random.choice(['Low', 'Medium', 'High'], n),

    # Binary
    'HasCar': np.random.choice([0, 1], n),

    # High Cardinality
    'City': np.random.choice([f'City_{i}' for i in range(1, 11)], n)
})

df.head()

  Gender Color    Education Satisfaction  HasCar    City
0  Other  Blue  High School          Low       1  City_7
1   Male   Red    Bachelors         High       1  City_2
2  Other  Blue      Masters       Medium       1  City_3
3  Other   Red  High School         High       1  City_1
4   Male  Blue          PhD         High       1  City_5

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Gender        50 non-null     str
 1   Color         50 non-null     str
 2   Education     50 non-null     str
 3   Satisfaction  50 non-null     str
 4   HasCar        50 non-null     int64
 5   City          50 non-null     str
dtypes: int64(1), str(5)
memory usage: 2.5 KB

In [28]:
df.nunique()

Gender           3
Color            4
Education        4
Satisfaction     3
HasCar           2
City            10
dtype: int64

In [29]:
nominal_cats = ["Gender" , "Color" , "City" , "HasCar"]

In [30]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder , OrdinalEncoder

#### Nominal Encoding

In [31]:
label_encoder = LabelEncoder()
label_encoder.fit_transform(df["Color"])

array([0, 2, 0, 2, 0, 3, 3, 1, 3, 1, 3, 2, 3, 1, 1, 0, 2, 3, 0, 3, 3, 0,
       0, 0, 0, 0, 3, 0, 2, 1, 0, 0, 3, 0, 0, 0, 3, 0, 1, 3, 1, 3, 0, 1,
       3, 2, 0, 3, 2, 3])

#### Ordinal Encoder

In [40]:
ordinal_cats = ["Education","Satisfaction"]
edu_order = ["High School" , "Bachelors" , "Masters" , "PhD"]
sats_order = ["Low" , "Medium" ,"High"]

ordinal_encoder = OrdinalEncoder(categories=[edu_order , sats_order])
ordinal_encoded = ordinal_encoder.fit_transform(df[ordinal_cats])

df_ordinal_encoded = pd.DataFrame( ordinal_encoded , columns = [f"{c}_encoded" for c in ordinal_cats] )

df_encoded = pd.concat([df , df_ordinal_encoded] , axis=1)
df_encoded.head()

,Gender,Color,Education,Satisfaction,HasCar,City,Education_encoded,Satisfaction_encoded
0,Other,Blue,High School,Low,1,City_7,0.0,0.0
1,Male,Red,Bachelors,High,1,City_2,1.0,2.0
2,Other,Blue,Masters,Medium,1,City_3,2.0,1.0
3,Other,Red,High School,High,1,City_1,0.0,2.0
4,Male,Blue,PhD,High,1,City_5,3.0,2.0

#### OneHotEncoder

In [59]:
nominal_cats = ["Gender" , "Color"] # Nominal Categories with low cardinality

ohe = OneHotEncoder(drop="first" ,sparse_output=False)
ohe_encoded = ohe.fit_transform(df[nominal_cats])

df_ohe_encoded = pd.DataFrame(ohe_encoded , columns=ohe.get_feature_names_out())

df_encoded = pd.concat([df_encoded , df_ohe_encoded] , axis=1)

df_encoded.head()

,Gender_Male,Gender_Other,Color_Green,Color_Red,Color_Yellow,Gender_Male,Gender_Other,Color_Green,Color_Red,Color_Yellow,...,Gender_Male,Gender_Other,Color_Green,Color_Red,Color_Yellow,Gender_Male,Gender_Other,Color_Green,Color_Red,Color_Yellow
0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0